// Global Energy Data by Country (2024-2025)
// Data includes: energy consumption, renewable %, fossil fuel %, nuclear %, energy mix, capacity
// Sources: IEA, IRENA, BP Statistical Review, World Bank Energy Database

const energyData = {
    // Renewable Energy Leaders
    "Iceland": {
        totalConsumption: 19.8,  // TWh per year
        renewablePercent: 85.4,
        fossilFuelPercent: 0.1,
        nuclearPercent: 0.0,
        hydro: 70.5,
        geothermal: 14.9,
        wind: 0.0,
        solar: 0.0,
        coal: 0.0,
        oil: 0.1,
        gas: 0.0,
        perCapita: 52500,  // kWh per person
        carbonIntensity: 12,  // gCO2/kWh
        energyIndependence: 100,
        rank: 1,
        status: "leader",
        color: "#10b981",
        trend: "stable",
        keyProjects: ["Geothermal expansion", "Hydro optimization"],
        targetYear: 2030,
        targetRenewable: 100
    },

    "Norway": {
        totalConsumption: 147.3,
        renewablePercent: 98.5,
        fossilFuelPercent: 1.5,
        nuclearPercent: 0.0,
        hydro: 95.2,
        wind: 3.3,
        solar: 0.0,
        coal: 0.2,
        oil: 1.3,
        gas: 0.0,
        perCapita: 27200,
        carbonIntensity: 15,
        energyIndependence: 95,
        rank: 2,
        status: "leader",
        color: "#10b981",
        trend: "growing",
        keyProjects: ["Wind power expansion", "Battery storage"],
        targetYear: 2030,
        targetRenewable: 100
    },

    "Sweden": {
        totalConsumption: 151.8,
        renewablePercent: 60.1,
        fossilFuelPercent: 9.4,
        nuclearPercent: 30.5,
        hydro: 40.5,
        wind: 17.3,
        solar: 2.3,
        coal: 2.1,
        oil: 4.2,
        gas: 3.1,
        nuclear: 30.5,
        perCapita: 14500,
        carbonIntensity: 25,
        energyIndependence: 65,
        rank: 3,
        status: "leader",
        color: "#10b981",
        trend: "growing",
        keyProjects: ["Offshore wind", "Nuclear modernization"],
        targetYear: 2040,
        targetRenewable: 100
    },

    "Costa Rica": {
        totalConsumption: 11.5,
        renewablePercent: 99.2,
        fossilFuelPercent: 0.8,
        nuclearPercent: 0.0,
        hydro: 73.4,
        geothermal: 13.2,
        wind: 10.3,
        solar: 2.3,
        coal: 0.0,
        oil: 0.8,
        gas: 0.0,
        perCapita: 2200,
        carbonIntensity: 10,
        energyIndependence: 85,
        rank: 4,
        status: "leader",
        color: "#10b981",
        trend: "stable",
        keyProjects: ["Solar expansion", "Grid modernization"],
        targetYear: 2025,
        targetRenewable: 100
    },

    "New Zealand": {
        totalConsumption: 42.8,
        renewablePercent: 82.4,
        fossilFuelPercent: 17.6,
        nuclearPercent: 0.0,
        hydro: 57.1,
        geothermal: 17.3,
        wind: 6.2,
        solar: 1.8,
        coal: 4.5,
        oil: 8.2,
        gas: 4.9,
        perCapita: 8500,
        carbonIntensity: 85,
        energyIndependence: 75,
        rank: 5,
        status: "leader",
        color: "#10b981",
        trend: "growing",
        keyProjects: ["Geothermal expansion", "Wind farms"],
        targetYear: 2035,
        targetRenewable: 100
    },

    // Major Economies
    "United States": {
        totalConsumption: 4050.2,
        renewablePercent: 21.5,
        fossilFuelPercent: 59.8,
        nuclearPercent: 18.7,
        hydro: 6.2,
        wind: 9.3,
        solar: 3.9,
        biomass: 2.1,
        coal: 19.5,
        oil: 2.1,
        gas: 38.2,
        nuclear: 18.7,
        perCapita: 12100,
        carbonIntensity: 420,
        energyIndependence: 105,
        rank: 28,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Solar boom", "Offshore wind", "Grid upgrade"],
        targetYear: 2050,
        targetRenewable: 100
    },

    "United States of America": {
        totalConsumption: 4050.2,
        renewablePercent: 21.5,
        fossilFuelPercent: 59.8,
        nuclearPercent: 18.7,
        hydro: 6.2,
        wind: 9.3,
        solar: 3.9,
        biomass: 2.1,
        coal: 19.5,
        oil: 2.1,
        gas: 38.2,
        nuclear: 18.7,
        perCapita: 12100,
        carbonIntensity: 420,
        energyIndependence: 105,
        rank: 28,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Solar boom", "Offshore wind", "Grid upgrade"],
        targetYear: 2050,
        targetRenewable: 100
    },

    "China": {
        totalConsumption: 8540.0,
        renewablePercent: 28.8,
        fossilFuelPercent: 62.3,
        nuclearPercent: 4.9,
        hydro: 16.4,
        wind: 7.8,
        solar: 4.2,
        biomass: 0.4,
        coal: 56.2,
        oil: 1.8,
        gas: 4.3,
        nuclear: 4.9,
        perCapita: 6000,
        carbonIntensity: 580,
        energyIndependence: 75,
        rank: 22,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Massive solar", "Wind capacity", "Nuclear expansion"],
        targetYear: 2060,
        targetRenewable: 80
    },

    "Germany": {
        totalConsumption: 525.8,
        renewablePercent: 46.2,
        fossilFuelPercent: 42.6,
        nuclearPercent: 6.0,
        hydro: 3.5,
        wind: 23.4,
        solar: 10.3,
        biomass: 9.0,
        coal: 26.8,
        oil: 0.9,
        gas: 14.9,
        nuclear: 6.0,
        perCapita: 6300,
        carbonIntensity: 385,
        energyIndependence: 35,
        rank: 8,
        status: "transition",
        color: "#10b981",
        trend: "improving",
        keyProjects: ["Energiewende", "Coal phaseout", "Green hydrogen"],
        targetYear: 2045,
        targetRenewable: 100
    },

    "France": {
        totalConsumption: 479.2,
        renewablePercent: 23.4,
        fossilFuelPercent: 9.8,
        nuclearPercent: 66.8,
        hydro: 11.2,
        wind: 8.3,
        solar: 3.9,
        biomass: 0.0,
        coal: 0.5,
        oil: 1.2,
        gas: 8.1,
        nuclear: 66.8,
        perCapita: 7400,
        carbonIntensity: 55,
        energyIndependence: 55,
        rank: 11,
        status: "leader",
        color: "#10b981",
        trend: "stable",
        keyProjects: ["Nuclear new build", "Offshore wind", "Solar expansion"],
        targetYear: 2050,
        targetRenewable: 40
    },

    "United Kingdom": {
        totalConsumption: 319.4,
        renewablePercent: 43.1,
        fossilFuelPercent: 40.8,
        nuclearPercent: 16.1,
        hydro: 1.8,
        wind: 26.8,
        solar: 4.2,
        biomass: 10.3,
        coal: 1.8,
        oil: 0.5,
        gas: 38.5,
        nuclear: 16.1,
        perCapita: 4700,
        carbonIntensity: 230,
        energyIndependence: 60,
        rank: 7,
        status: "transition",
        color: "#10b981",
        trend: "improving",
        keyProjects: ["Offshore wind leader", "Nuclear revival", "Coal exit"],
        targetYear: 2050,
        targetRenewable: 100
    },

    "Japan": {
        totalConsumption: 937.5,
        renewablePercent: 20.3,
        fossilFuelPercent: 73.2,
        nuclearPercent: 6.5,
        hydro: 7.8,
        wind: 0.9,
        solar: 8.5,
        biomass: 3.1,
        coal: 26.9,
        oil: 6.1,
        gas: 40.2,
        nuclear: 6.5,
        perCapita: 7600,
        carbonIntensity: 510,
        energyIndependence: 12,
        rank: 35,
        status: "transition",
        color: "#f59e0b",
        trend: "slow",
        keyProjects: ["Solar expansion", "Offshore wind", "Nuclear restart"],
        targetYear: 2050,
        targetRenewable: 50
    },

    "Brazil": {
        totalConsumption: 629.6,
        renewablePercent: 84.8,
        fossilFuelPercent: 15.2,
        nuclearPercent: 2.5,
        hydro: 63.8,
        wind: 11.2,
        solar: 2.9,
        biomass: 6.9,
        coal: 2.8,
        oil: 5.2,
        gas: 7.2,
        nuclear: 2.5,
        perCapita: 2900,
        carbonIntensity: 95,
        energyIndependence: 90,
        rank: 6,
        status: "leader",
        color: "#10b981",
        trend: "stable",
        keyProjects: ["Wind expansion", "Solar growth", "Hydro optimization"],
        targetYear: 2030,
        targetRenewable: 93
    },

    "India": {
        totalConsumption: 1730.5,
        renewablePercent: 23.0,
        fossilFuelPercent: 73.2,
        nuclearPercent: 3.8,
        hydro: 9.8,
        wind: 4.2,
        solar: 7.1,
        biomass: 1.9,
        coal: 70.6,
        oil: 0.8,
        gas: 1.8,
        nuclear: 3.8,
        perCapita: 1200,
        carbonIntensity: 720,
        energyIndependence: 70,
        rank: 34,
        status: "transition",
        color: "#f59e0b",
        trend: "improving",
        keyProjects: ["Massive solar rollout", "Wind capacity", "Green hydrogen"],
        targetYear: 2070,
        targetRenewable: 50
    },

    "Canada": {
        totalConsumption: 638.2,
        renewablePercent: 67.5,
        fossilFuelPercent: 26.1,
        nuclearPercent: 14.6,
        hydro: 59.3,
        wind: 5.2,
        solar: 0.3,
        biomass: 2.7,
        coal: 5.8,
        oil: 1.1,
        gas: 19.2,
        nuclear: 14.6,
        perCapita: 16000,
        carbonIntensity: 140,
        energyIndependence: 180,
        rank: 9,
        status: "leader",
        color: "#10b981",
        trend: "stable",
        keyProjects: ["Hydro expansion", "Wind growth", "Nuclear SMRs"],
        targetYear: 2050,
        targetRenewable: 90
    },

    "Australia": {
        totalConsumption: 265.3,
        renewablePercent: 32.5,
        fossilFuelPercent: 67.5,
        nuclearPercent: 0.0,
        hydro: 5.8,
        wind: 10.7,
        solar: 14.1,
        biomass: 1.9,
        coal: 52.3,
        oil: 1.2,
        gas: 14.0,
        perCapita: 10200,
        carbonIntensity: 650,
        energyIndependence: 320,
        rank: 23,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Rooftop solar boom", "Battery storage", "Offshore wind"],
        targetYear: 2050,
        targetRenewable: 82
    },

    "Spain": {
        totalConsumption: 265.9,
        renewablePercent: 47.4,
        fossilFuelPercent: 36.1,
        nuclearPercent: 20.8,
        hydro: 11.3,
        wind: 23.3,
        solar: 11.1,
        biomass: 1.7,
        coal: 2.1,
        oil: 2.8,
        gas: 31.2,
        nuclear: 20.8,
        perCapita: 5600,
        carbonIntensity: 180,
        energyIndependence: 30,
        rank: 10,
        status: "transition",
        color: "#10b981",
        trend: "improving",
        keyProjects: ["Solar expansion", "Wind leader", "Green hydrogen"],
        targetYear: 2050,
        targetRenewable: 74
    },

    "Italy": {
        totalConsumption: 313.8,
        renewablePercent: 40.4,
        fossilFuelPercent: 59.6,
        nuclearPercent: 0.0,
        hydro: 16.2,
        wind: 7.1,
        solar: 9.2,
        biomass: 7.9,
        coal: 4.8,
        oil: 3.1,
        gas: 51.7,
        perCapita: 5300,
        carbonIntensity: 315,
        energyIndependence: 25,
        rank: 14,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Solar growth", "Wind expansion", "Gas reduction"],
        targetYear: 2050,
        targetRenewable: 65
    },

    "South Korea": {
        totalConsumption: 612.4,
        renewablePercent: 7.5,
        fossilFuelPercent: 63.4,
        nuclearPercent: 29.1,
        hydro: 0.4,
        wind: 0.6,
        solar: 5.1,
        biomass: 1.4,
        coal: 34.6,
        oil: 1.9,
        gas: 26.9,
        nuclear: 29.1,
        perCapita: 11800,
        carbonIntensity: 470,
        energyIndependence: 18,
        rank: 45,
        status: "lagging",
        color: "#ef4444",
        trend: "slow",
        keyProjects: ["Offshore wind", "Solar expansion", "Nuclear expansion"],
        targetYear: 2050,
        targetRenewable: 40
    },

    "Denmark": {
        totalConsumption: 33.4,
        renewablePercent: 77.0,
        fossilFuelPercent: 23.0,
        nuclearPercent: 0.0,
        hydro: 0.1,
        wind: 55.2,
        solar: 5.1,
        biomass: 16.6,
        coal: 8.4,
        oil: 2.8,
        gas: 11.8,
        perCapita: 5700,
        carbonIntensity: 120,
        energyIndependence: 60,
        rank: 12,
        status: "leader",
        color: "#10b981",
        trend: "growing",
        keyProjects: ["Offshore wind pioneer", "Energy islands", "Green hydrogen"],
        targetYear: 2030,
        targetRenewable: 100
    },

    "Portugal": {
        totalConsumption: 51.2,
        renewablePercent: 58.4,
        fossilFuelPercent: 41.6,
        nuclearPercent: 0.0,
        hydro: 25.7,
        wind: 25.1,
        solar: 5.1,
        biomass: 2.5,
        coal: 7.2,
        oil: 1.8,
        gas: 32.6,
        perCapita: 5000,
        carbonIntensity: 210,
        energyIndependence: 45,
        rank: 13,
        status: "transition",
        color: "#10b981",
        trend: "improving",
        keyProjects: ["Solar expansion", "Wind growth", "Coal phaseout"],
        targetYear: 2040,
        targetRenewable: 80
    },

    "Netherlands": {
        totalConsumption: 119.3,
        renewablePercent: 15.0,
        fossilFuelPercent: 85.0,
        nuclearPercent: 3.1,
        hydro: 0.0,
        wind: 10.9,
        solar: 3.2,
        biomass: 0.9,
        coal: 11.2,
        oil: 0.8,
        gas: 73.0,
        nuclear: 3.1,
        perCapita: 6800,
        carbonIntensity: 425,
        energyIndependence: 45,
        rank: 42,
        status: "lagging",
        color: "#ef4444",
        trend: "slow",
        keyProjects: ["Offshore wind", "Solar growth", "Gas phase-down"],
        targetYear: 2050,
        targetRenewable: 70
    },

    "Poland": {
        totalConsumption: 171.4,
        renewablePercent: 16.1,
        fossilFuelPercent: 83.9,
        nuclearPercent: 0.0,
        hydro: 1.6,
        wind: 9.2,
        solar: 4.6,
        biomass: 0.7,
        coal: 70.8,
        oil: 1.9,
        gas: 11.2,
        perCapita: 4500,
        carbonIntensity: 730,
        energyIndependence: 55,
        rank: 44,
        status: "lagging",
        color: "#ef4444",
        trend: "slow",
        keyProjects: ["First nuclear plants", "Wind expansion", "Coal reduction"],
        targetYear: 2049,
        targetRenewable: 50
    },

    "Turkey": {
        totalConsumption: 330.6,
        renewablePercent: 44.3,
        fossilFuelPercent: 55.7,
        nuclearPercent: 0.0,
        hydro: 26.7,
        wind: 10.3,
        solar: 5.6,
        geothermal: 1.7,
        coal: 37.1,
        oil: 1.1,
        gas: 17.5,
        perCapita: 3900,
        carbonIntensity: 410,
        energyIndependence: 30,
        rank: 15,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Renewable expansion", "Nuclear build", "Coal reduction"],
        targetYear: 2053,
        targetRenewable: 65
    },

    "Saudi Arabia": {
        totalConsumption: 395.8,
        renewablePercent: 0.4,
        fossilFuelPercent: 99.6,
        nuclearPercent: 0.0,
        hydro: 0.0,
        wind: 0.1,
        solar: 0.3,
        coal: 0.0,
        oil: 47.2,
        gas: 52.4,
        perCapita: 10700,
        carbonIntensity: 620,
        energyIndependence: 1800,
        rank: 50,
        status: "lagging",
        color: "#dc2626",
        trend: "starting",
        keyProjects: ["Vision 2030", "Solar megaprojects", "Wind farms"],
        targetYear: 2030,
        targetRenewable: 50
    },

    "UAE": {
        totalConsumption: 138.7,
        renewablePercent: 3.9,
        fossilFuelPercent: 93.9,
        nuclearPercent: 2.2,
        hydro: 0.0,
        wind: 0.1,
        solar: 3.8,
        coal: 0.0,
        oil: 1.2,
        gas: 92.7,
        nuclear: 2.2,
        perCapita: 14000,
        carbonIntensity: 490,
        energyIndependence: 180,
        rank: 48,
        status: "lagging",
        color: "#ef4444",
        trend: "starting",
        keyProjects: ["Nuclear expansion", "Solar parks", "Green hydrogen"],
        targetYear: 2050,
        targetRenewable: 50
    },

    "South Africa": {
        totalConsumption: 234.2,
        renewablePercent: 7.8,
        fossilFuelPercent: 88.5,
        nuclearPercent: 3.7,
        hydro: 1.2,
        wind: 3.8,
        solar: 2.8,
        coal: 84.1,
        oil: 0.8,
        gas: 3.6,
        nuclear: 3.7,
        perCapita: 3900,
        carbonIntensity: 880,
        energyIndependence: 95,
        rank: 47,
        status: "lagging",
        color: "#ef4444",
        trend: "starting",
        keyProjects: ["Renewable IPPs", "Just transition", "Solar+storage"],
        targetYear: 2050,
        targetRenewable: 50
    },

    "Mexico": {
        totalConsumption: 318.5,
        renewablePercent: 26.9,
        fossilFuelPercent: 69.4,
        nuclearPercent: 3.7,
        hydro: 9.8,
        wind: 7.8,
        solar: 5.1,
        geothermal: 1.2,
        biomass: 3.0,
        coal: 6.8,
        oil: 9.2,
        gas: 53.4,
        nuclear: 3.7,
        perCapita: 2500,
        carbonIntensity: 460,
        energyIndependence: 55,
        rank: 26,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Solar expansion", "Wind growth", "Grid modernization"],
        targetYear: 2050,
        targetRenewable: 50
    },

    "Chile": {
        totalConsumption: 80.2,
        renewablePercent: 46.2,
        fossilFuelPercent: 53.8,
        nuclearPercent: 0.0,
        hydro: 26.3,
        wind: 8.1,
        solar: 11.4,
        biomass: 0.4,
        coal: 28.2,
        oil: 3.1,
        gas: 22.5,
        perCapita: 4200,
        carbonIntensity: 380,
        energyIndependence: 25,
        rank: 16,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Solar boom", "Coal phaseout", "Green hydrogen"],
        targetYear: 2050,
        targetRenewable: 80
    },

    "Argentina": {
        totalConsumption: 142.8,
        renewablePercent: 31.4,
        fossilFuelPercent: 67.5,
        nuclearPercent: 7.4,
        hydro: 26.8,
        wind: 3.2,
        solar: 0.8,
        biomass: 0.6,
        coal: 1.8,
        oil: 4.9,
        gas: 60.8,
        nuclear: 7.4,
        perCapita: 3100,
        carbonIntensity: 340,
        energyIndependence: 80,
        rank: 21,
        status: "transition",
        color: "#3b82f6",
        trend: "stable",
        keyProjects: ["Vaca Muerta gas", "Wind expansion", "Solar growth"],
        targetYear: 2050,
        targetRenewable: 50
    },

    "Indonesia": {
        totalConsumption: 278.3,
        renewablePercent: 12.3,
        fossilFuelPercent: 87.7,
        nuclearPercent: 0.0,
        hydro: 6.1,
        geothermal: 4.8,
        wind: 0.1,
        solar: 0.3,
        biomass: 1.0,
        coal: 61.8,
        oil: 5.2,
        gas: 20.7,
        perCapita: 1000,
        carbonIntensity: 710,
        energyIndependence: 130,
        rank: 43,
        status: "lagging",
        color: "#ef4444",
        trend: "slow",
        keyProjects: ["Geothermal expansion", "Solar growth", "Coal reduction"],
        targetYear: 2060,
        targetRenewable: 31
    },

    "Thailand": {
        totalConsumption: 195.4,
        renewablePercent: 14.1,
        fossilFuelPercent: 85.9,
        nuclearPercent: 0.0,
        hydro: 3.2,
        wind: 1.8,
        solar: 6.9,
        biomass: 2.2,
        coal: 19.2,
        oil: 1.8,
        gas: 64.9,
        perCapita: 2700,
        carbonIntensity: 520,
        energyIndependence: 45,
        rank: 40,
        status: "lagging",
        color: "#ef4444",
        trend: "slow",
        keyProjects: ["Solar expansion", "Wind growth", "Gas imports"],
        targetYear: 2050,
        targetRenewable: 50
    },

    "Vietnam": {
        totalConsumption: 245.2,
        renewablePercent: 28.2,
        fossilFuelPercent: 71.8,
        nuclearPercent: 0.0,
        hydro: 19.8,
        wind: 4.1,
        solar: 4.1,
        biomass: 0.2,
        coal: 47.3,
        oil: 0.8,
        gas: 23.7,
        perCapita: 2500,
        carbonIntensity: 580,
        energyIndependence: 60,
        rank: 24,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Solar boom", "Wind expansion", "Coal reduction"],
        targetYear: 2050,
        targetRenewable: 50
    },

    "Philippines": {
        totalConsumption: 106.4,
        renewablePercent: 33.4,
        fossilFuelPercent: 66.6,
        nuclearPercent: 0.0,
        hydro: 10.2,
        geothermal: 9.8,
        wind: 1.2,
        solar: 2.2,
        biomass: 10.0,
        coal: 57.1,
        oil: 3.2,
        gas: 6.3,
        perCapita: 900,
        carbonIntensity: 610,
        energyIndependence: 40,
        rank: 20,
        status: "transition",
        color: "#3b82f6",
        trend: "stable",
        keyProjects: ["Renewable energy", "Geothermal expansion", "Solar growth"],
        targetYear: 2040,
        targetRenewable: 35
    },

    "Kenya": {
        totalConsumption: 11.9,
        renewablePercent: 90.1,
        fossilFuelPercent: 9.9,
        nuclearPercent: 0.0,
        hydro: 34.2,
        geothermal: 46.2,
        wind: 8.3,
        solar: 1.4,
        coal: 0.0,
        oil: 9.9,
        gas: 0.0,
        perCapita: 220,
        carbonIntensity: 35,
        energyIndependence: 70,
        rank: 17,
        status: "leader",
        color: "#10b981",
        trend: "growing",
        keyProjects: ["Geothermal leader", "Wind expansion", "Solar mini-grids"],
        targetYear: 2030,
        targetRenewable: 100
    },

    "Morocco": {
        totalConsumption: 35.8,
        renewablePercent: 37.6,
        fossilFuelPercent: 62.4,
        nuclearPercent: 0.0,
        hydro: 11.2,
        wind: 12.8,
        solar: 13.6,
        coal: 51.2,
        oil: 3.8,
        gas: 7.4,
        perCapita: 950,
        carbonIntensity: 520,
        energyIndependence: 10,
        rank: 18,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Noor solar complex", "Wind farms", "Green hydrogen"],
        targetYear: 2030,
        targetRenewable: 52
    },

    "Egypt": {
        totalConsumption: 198.7,
        renewablePercent: 11.4,
        fossilFuelPercent: 88.6,
        nuclearPercent: 0.0,
        hydro: 5.8,
        wind: 3.1,
        solar: 2.5,
        coal: 0.8,
        oil: 7.2,
        gas: 80.6,
        perCapita: 1800,
        carbonIntensity: 520,
        energyIndependence: 90,
        rank: 41,
        status: "lagging",
        color: "#ef4444",
        trend: "starting",
        keyProjects: ["Benban solar park", "Wind expansion", "Nuclear build"],
        targetYear: 2035,
        targetRenewable: 42
    },

    "Pakistan": {
        totalConsumption: 127.4,
        renewablePercent: 31.9,
        fossilFuelPercent: 64.4,
        nuclearPercent: 3.7,
        hydro: 27.1,
        wind: 2.9,
        solar: 1.2,
        biomass: 0.7,
        coal: 12.8,
        oil: 28.9,
        gas: 22.7,
        nuclear: 3.7,
        perCapita: 530,
        carbonIntensity: 490,
        energyIndependence: 55,
        rank: 25,
        status: "transition",
        color: "#3b82f6",
        trend: "stable",
        keyProjects: ["Hydro expansion", "Solar growth", "Wind farms"],
        targetYear: 2030,
        targetRenewable: 60
    },

    "Bangladesh": {
        totalConsumption: 79.5,
        renewablePercent: 3.7,
        fossilFuelPercent: 96.3,
        nuclearPercent: 0.0,
        hydro: 1.2,
        wind: 0.0,
        solar: 2.5,
        coal: 2.8,
        oil: 18.1,
        gas: 75.4,
        perCapita: 460,
        carbonIntensity: 580,
        energyIndependence: 20,
        rank: 49,
        status: "lagging",
        color: "#dc2626",
        trend: "starting",
        keyProjects: ["Solar home systems", "Nuclear build", "Gas imports"],
        targetYear: 2041,
        targetRenewable: 40
    },

    "Nigeria": {
        totalConsumption: 30.5,
        renewablePercent: 81.5,
        fossilFuelPercent: 18.5,
        nuclearPercent: 0.0,
        hydro: 80.2,
        wind: 0.0,
        solar: 1.3,
        coal: 0.0,
        oil: 8.2,
        gas: 10.3,
        perCapita: 130,
        carbonIntensity: 140,
        energyIndependence: 150,
        rank: 19,
        status: "transition",
        color: "#3b82f6",
        trend: "potential",
        keyProjects: ["Solar expansion", "Hydro rehabilitation", "Off-grid solutions"],
        targetYear: 2030,
        targetRenewable: 30
    },

    "Russia": {
        totalConsumption: 1115.8,
        renewablePercent: 20.9,
        fossilFuelPercent: 62.9,
        nuclearPercent: 20.3,
        hydro: 19.1,
        wind: 0.1,
        solar: 0.2,
        biomass: 1.5,
        coal: 16.2,
        oil: 2.1,
        gas: 44.6,
        nuclear: 20.3,
        perCapita: 7700,
        carbonIntensity: 380,
        energyIndependence: 220,
        rank: 30,
        status: "transition",
        color: "#3b82f6",
        trend: "slow",
        keyProjects: ["Nuclear expansion", "Hydro growth", "Gas dominance"],
        targetYear: 2060,
        targetRenewable: 50
    },

    // Additional European Countries
    "Austria": {
        totalConsumption: 72.8,
        renewablePercent: 78.2,
        fossilFuelPercent: 21.8,
        nuclearPercent: 0.0,
        hydro: 59.8,
        wind: 10.2,
        solar: 3.1,
        biomass: 5.1,
        coal: 7.8,
        oil: 3.2,
        gas: 10.8,
        perCapita: 8100,
        carbonIntensity: 110,
        energyIndependence: 55,
        rank: 27,
        status: "leader",
        color: "#10b981",
        trend: "stable",
        keyProjects: ["Hydro optimization", "Wind expansion", "Coal exit"],
        targetYear: 2040,
        targetRenewable: 100
    },

    "Belgium": {
        totalConsumption: 87.4,
        renewablePercent: 19.4,
        fossilFuelPercent: 30.8,
        nuclearPercent: 49.8,
        hydro: 0.4,
        wind: 11.8,
        solar: 5.2,
        biomass: 2.0,
        coal: 2.1,
        oil: 0.8,
        gas: 27.9,
        nuclear: 49.8,
        perCapita: 7600,
        carbonIntensity: 180,
        energyIndependence: 25,
        rank: 37,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Offshore wind", "Nuclear debate", "Solar growth"],
        targetYear: 2050,
        targetRenewable: 70
    },

    "Switzerland": {
        totalConsumption: 62.1,
        renewablePercent: 75.3,
        fossilFuelPercent: 5.2,
        nuclearPercent: 32.9,
        hydro: 57.8,
        wind: 0.2,
        solar: 4.8,
        biomass: 2.5,
        coal: 0.0,
        oil: 1.2,
        gas: 4.0,
        nuclear: 32.9,
        perCapita: 7200,
        carbonIntensity: 35,
        energyIndependence: 60,
        rank: 29,
        status: "leader",
        color: "#10b981",
        trend: "stable",
        keyProjects: ["Hydro storage", "Solar Alpine", "Nuclear phaseout"],
        targetYear: 2050,
        targetRenewable: 100
    },

    "Finland": {
        totalConsumption: 85.2,
        renewablePercent: 47.3,
        fossilFuelPercent: 20.8,
        nuclearPercent: 31.9,
        hydro: 20.1,
        wind: 11.2,
        biomass: 16.0,
        coal: 6.8,
        oil: 2.1,
        gas: 11.9,
        nuclear: 31.9,
        perCapita: 15400,
        carbonIntensity: 95,
        energyIndependence: 45,
        rank: 31,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["New nuclear", "Wind expansion", "Biomass CHP"],
        targetYear: 2035,
        targetRenewable: 50
    },

    "Greece": {
        totalConsumption: 54.2,
        renewablePercent: 43.8,
        fossilFuelPercent: 56.2,
        nuclearPercent: 0.0,
        hydro: 10.2,
        wind: 21.3,
        solar: 12.3,
        coal: 12.8,
        oil: 2.1,
        gas: 41.3,
        perCapita: 5100,
        carbonIntensity: 420,
        energyIndependence: 35,
        rank: 32,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Lignite phaseout", "Island renewables", "Solar boom"],
        targetYear: 2030,
        targetRenewable: 61
    },

    "Czech Republic": {
        totalConsumption: 86.7,
        renewablePercent: 16.2,
        fossilFuelPercent: 46.1,
        nuclearPercent: 37.7,
        hydro: 3.8,
        wind: 0.9,
        solar: 3.2,
        biomass: 8.3,
        coal: 40.8,
        oil: 0.8,
        gas: 4.5,
        nuclear: 37.7,
        perCapita: 8100,
        carbonIntensity: 510,
        energyIndependence: 45,
        rank: 38,
        status: "transition",
        color: "#3b82f6",
        trend: "slow",
        keyProjects: ["Nuclear expansion", "Coal reduction", "Solar growth"],
        targetYear: 2050,
        targetRenewable: 30
    },

    "Romania": {
        totalConsumption: 63.8,
        renewablePercent: 43.1,
        fossilFuelPercent: 38.2,
        nuclearPercent: 18.7,
        hydro: 28.2,
        wind: 11.8,
        solar: 3.1,
        coal: 18.2,
        oil: 2.8,
        gas: 17.2,
        nuclear: 18.7,
        perCapita: 3300,
        carbonIntensity: 310,
        energyIndependence: 70,
        rank: 33,
        status: "transition",
        color: "#3b82f6",
        trend: "stable",
        keyProjects: ["Wind expansion", "Hydro rehabilitation", "Nuclear modernization"],
        targetYear: 2050,
        targetRenewable: 55
    },

    "Ireland": {
        totalConsumption: 32.4,
        renewablePercent: 38.6,
        fossilFuelPercent: 61.4,
        nuclearPercent: 0.0,
        hydro: 2.8,
        wind: 32.1,
        solar: 0.2,
        biomass: 3.5,
        coal: 4.2,
        oil: 4.8,
        gas: 52.4,
        perCapita: 6400,
        carbonIntensity: 340,
        energyIndependence: 30,
        rank: 36,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Offshore wind boom", "Solar growth", "Gas reduction"],
        targetYear: 2050,
        targetRenewable: 80
    },

    "Hungary": {
        totalConsumption: 48.2,
        renewablePercent: 14.6,
        fossilFuelPercent: 49.8,
        nuclearPercent: 35.6,
        hydro: 0.6,
        wind: 2.1,
        solar: 9.8,
        biomass: 2.1,
        coal: 8.2,
        oil: 1.8,
        gas: 39.8,
        nuclear: 35.6,
        perCapita: 4900,
        carbonIntensity: 290,
        energyIndependence: 35,
        rank: 39,
        status: "lagging",
        color: "#ef4444",
        trend: "slow",
        keyProjects: ["Nuclear expansion", "Solar boom", "Gas dependence"],
        targetYear: 2050,
        targetRenewable: 90
    },

    // Additional Asian Countries
    "Malaysia": {
        totalConsumption: 167.2,
        renewablePercent: 8.2,
        fossilFuelPercent: 91.8,
        nuclearPercent: 0.0,
        hydro: 6.8,
        solar: 1.2,
        biomass: 0.2,
        coal: 39.8,
        oil: 1.2,
        gas: 50.8,
        perCapita: 5200,
        carbonIntensity: 690,
        energyIndependence: 90,
        rank: 46,
        status: "lagging",
        color: "#ef4444",
        trend: "starting",
        keyProjects: ["Solar expansion", "Hydro projects", "Coal reduction"],
        targetYear: 2050,
        targetRenewable: 31
    },

    "Singapore": {
        totalConsumption: 53.8,
        renewablePercent: 2.1,
        fossilFuelPercent: 97.9,
        nuclearPercent: 0.0,
        hydro: 0.0,
        solar: 2.1,
        coal: 0.0,
        oil: 1.8,
        gas: 96.1,
        perCapita: 9200,
        carbonIntensity: 410,
        energyIndependence: 5,
        rank: 51,
        status: "lagging",
        color: "#dc2626",
        trend: "starting",
        keyProjects: ["Solar rooftop", "Regional grid", "LNG imports"],
        targetYear: 2050,
        targetRenewable: 5
    },

    "Taiwan": {
        totalConsumption: 282.4,
        renewablePercent: 8.3,
        fossilFuelPercent: 82.4,
        nuclearPercent: 9.3,
        hydro: 1.8,
        wind: 1.2,
        solar: 3.8,
        biomass: 1.5,
        coal: 45.2,
        oil: 2.1,
        gas: 35.1,
        nuclear: 9.3,
        perCapita: 11900,
        carbonIntensity: 620,
        energyIndependence: 2,
        rank: 52,
        status: "lagging",
        color: "#dc2626",
        trend: "improving",
        keyProjects: ["Offshore wind", "Solar expansion", "Nuclear phaseout"],
        targetYear: 2050,
        targetRenewable: 20
    },

    "Myanmar": {
        totalConsumption: 19.2,
        renewablePercent: 62.1,
        fossilFuelPercent: 37.9,
        nuclearPercent: 0.0,
        hydro: 61.8,
        solar: 0.2,
        biomass: 0.1,
        coal: 0.8,
        oil: 1.2,
        gas: 35.9,
        perCapita: 350,
        carbonIntensity: 280,
        energyIndependence: 110,
        rank: 53,
        status: "transition",
        color: "#3b82f6",
        trend: "potential",
        keyProjects: ["Hydro development", "Solar mini-grids", "Gas exports"],
        targetYear: 2030,
        targetRenewable: 80
    },

    "Nepal": {
        totalConsumption: 6.8,
        renewablePercent: 98.8,
        fossilFuelPercent: 1.2,
        nuclearPercent: 0.0,
        hydro: 98.2,
        solar: 0.6,
        coal: 0.0,
        oil: 1.2,
        gas: 0.0,
        perCapita: 230,
        carbonIntensity: 8,
        energyIndependence: 40,
        rank: 54,
        status: "leader",
        color: "#10b981",
        trend: "growing",
        keyProjects: ["Hydro expansion", "Solar home systems", "Grid development"],
        targetYear: 2030,
        targetRenewable: 100
    },

    "Sri Lanka": {
        totalConsumption: 15.4,
        renewablePercent: 53.2,
        fossilFuelPercent: 46.8,
        nuclearPercent: 0.0,
        hydro: 41.2,
        wind: 4.8,
        solar: 2.1,
        biomass: 5.1,
        coal: 39.8,
        oil: 6.2,
        gas: 0.8,
        perCapita: 710,
        carbonIntensity: 420,
        energyIndependence: 35,
        rank: 55,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Wind expansion", "Solar rooftop", "Coal imports"],
        targetYear: 2050,
        targetRenewable: 70
    },

    // Additional Latin American Countries
    "Colombia": {
        totalConsumption: 76.8,
        renewablePercent: 71.4,
        fossilFuelPercent: 28.6,
        nuclearPercent: 0.0,
        hydro: 67.8,
        wind: 0.2,
        solar: 1.2,
        biomass: 2.2,
        coal: 8.2,
        oil: 2.1,
        gas: 18.3,
        perCapita: 1500,
        carbonIntensity: 180,
        energyIndependence: 110,
        rank: 56,
        status: "leader",
        color: "#10b981",
        trend: "stable",
        keyProjects: ["Hydro expansion", "Wind farms", "Solar growth"],
        targetYear: 2050,
        targetRenewable: 80
    },

    "Peru": {
        totalConsumption: 55.2,
        renewablePercent: 56.8,
        fossilFuelPercent: 43.2,
        nuclearPercent: 0.0,
        hydro: 52.1,
        wind: 1.8,
        solar: 2.4,
        biomass: 0.5,
        coal: 2.8,
        oil: 3.2,
        gas: 37.2,
        perCapita: 1700,
        carbonIntensity: 270,
        energyIndependence: 95,
        rank: 57,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Hydro projects", "Solar Andean", "Wind coast"],
        targetYear: 2050,
        targetRenewable: 70
    },

    "Ecuador": {
        totalConsumption: 28.4,
        renewablePercent: 79.2,
        fossilFuelPercent: 20.8,
        nuclearPercent: 0.0,
        hydro: 77.8,
        wind: 0.2,
        solar: 0.8,
        biomass: 0.4,
        coal: 0.0,
        oil: 18.2,
        gas: 2.6,
        perCapita: 1600,
        carbonIntensity: 140,
        energyIndependence: 160,
        rank: 58,
        status: "leader",
        color: "#10b981",
        trend: "stable",
        keyProjects: ["Hydro optimization", "Solar expansion", "Oil reduction"],
        targetYear: 2050,
        targetRenewable: 90
    },

    "Uruguay": {
        totalConsumption: 12.4,
        renewablePercent: 94.5,
        fossilFuelPercent: 5.5,
        nuclearPercent: 0.0,
        hydro: 43.2,
        wind: 38.4,
        solar: 3.8,
        biomass: 9.1,
        coal: 0.0,
        oil: 5.5,
        gas: 0.0,
        perCapita: 3600,
        carbonIntensity: 35,
        energyIndependence: 70,
        rank: 59,
        status: "leader",
        color: "#10b981",
        trend: "stable",
        keyProjects: ["Wind leader", "Solar farms", "Battery storage"],
        targetYear: 2030,
        targetRenewable: 100
    },

    "Venezuela": {
        totalConsumption: 91.2,
        renewablePercent: 67.8,
        fossilFuelPercent: 32.2,
        nuclearPercent: 0.0,
        hydro: 67.8,
        wind: 0.0,
        solar: 0.0,
        coal: 0.0,
        oil: 12.1,
        gas: 20.1,
        perCapita: 3200,
        carbonIntensity: 190,
        energyIndependence: 550,
        rank: 60,
        status: "transition",
        color: "#3b82f6",
        trend: "declining",
        keyProjects: ["Guri Dam", "Infrastructure crisis", "Oil exports"],
        targetYear: 2030,
        targetRenewable: 80
    },

    // Additional African Countries
    "Ethiopia": {
        totalConsumption: 13.8,
        renewablePercent: 99.8,
        fossilFuelPercent: 0.2,
        nuclearPercent: 0.0,
        hydro: 97.8,
        wind: 1.8,
        solar: 0.2,
        coal: 0.0,
        oil: 0.2,
        gas: 0.0,
        perCapita: 120,
        carbonIntensity: 5,
        energyIndependence: 40,
        rank: 61,
        status: "leader",
        color: "#10b981",
        trend: "growing",
        keyProjects: ["Grand Renaissance Dam", "Wind farms", "Rural electrification"],
        targetYear: 2030,
        targetRenewable: 100
    },

    "Ghana": {
        totalConsumption: 17.2,
        renewablePercent: 58.4,
        fossilFuelPercent: 41.6,
        nuclearPercent: 0.0,
        hydro: 44.8,
        solar: 1.2,
        biomass: 12.4,
        coal: 0.0,
        oil: 22.8,
        gas: 18.8,
        perCapita: 540,
        carbonIntensity: 280,
        energyIndependence: 85,
        rank: 62,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Solar expansion", "Hydro optimization", "Gas development"],
        targetYear: 2030,
        targetRenewable: 70
    },

    "Tanzania": {
        totalConsumption: 7.2,
        renewablePercent: 89.2,
        fossilFuelPercent: 10.8,
        nuclearPercent: 0.0,
        hydro: 32.8,
        wind: 0.0,
        solar: 1.2,
        biomass: 55.2,
        coal: 3.2,
        oil: 6.8,
        gas: 0.8,
        perCapita: 120,
        carbonIntensity: 120,
        energyIndependence: 50,
        rank: 63,
        status: "transition",
        color: "#3b82f6",
        trend: "potential",
        keyProjects: ["Hydro expansion", "Solar mini-grids", "Gas discovery"],
        targetYear: 2030,
        targetRenewable: 75
    },

    "Algeria": {
        totalConsumption: 68.4,
        renewablePercent: 1.2,
        fossilFuelPercent: 98.8,
        nuclearPercent: 0.0,
        hydro: 0.6,
        solar: 0.6,
        coal: 0.0,
        oil: 21.2,
        gas: 77.6,
        perCapita: 1550,
        carbonIntensity: 580,
        energyIndependence: 850,
        rank: 64,
        status: "lagging",
        color: "#dc2626",
        trend: "starting",
        keyProjects: ["Solar megaproject", "Wind farms", "Shale gas"],
        targetYear: 2030,
        targetRenewable: 27
    },

    "Tunisia": {
        totalConsumption: 19.8,
        renewablePercent: 6.2,
        fossilFuelPercent: 93.8,
        nuclearPercent: 0.0,
        hydro: 0.4,
        wind: 3.8,
        solar: 2.0,
        coal: 0.0,
        oil: 18.2,
        gas: 75.6,
        perCapita: 1650,
        carbonIntensity: 510,
        energyIndependence: 45,
        rank: 65,
        status: "lagging",
        color: "#ef4444",
        trend: "improving",
        keyProjects: ["Solar Plan", "Wind expansion", "Energy efficiency"],
        targetYear: 2030,
        targetRenewable: 30
    },

    // Additional Middle Eastern Countries
    "Iran": {
        totalConsumption: 343.2,
        renewablePercent: 7.8,
        fossilFuelPercent: 92.2,
        nuclearPercent: 0.8,
        hydro: 6.2,
        wind: 0.8,
        solar: 0.8,
        coal: 0.8,
        oil: 9.2,
        gas: 82.2,
        nuclear: 0.8,
        perCapita: 3900,
        carbonIntensity: 620,
        energyIndependence: 140,
        rank: 66,
        status: "lagging",
        color: "#ef4444",
        trend: "slow",
        keyProjects: ["Nuclear program", "Solar potential", "Gas dominance"],
        targetYear: 2050,
        targetRenewable: 5
    },

    "Iraq": {
        totalConsumption: 58.2,
        renewablePercent: 3.2,
        fossilFuelPercent: 96.8,
        nuclearPercent: 0.0,
        hydro: 3.2,
        solar: 0.0,
        coal: 0.0,
        oil: 28.4,
        gas: 68.4,
        perCapita: 1400,
        carbonIntensity: 680,
        energyIndependence: 280,
        rank: 67,
        status: "lagging",
        color: "#dc2626",
        trend: "starting",
        keyProjects: ["Solar projects", "Gas flaring reduction", "Grid rebuild"],
        targetYear: 2030,
        targetRenewable: 12
    },

    "Kuwait": {
        totalConsumption: 67.8,
        renewablePercent: 0.8,
        fossilFuelPercent: 99.2,
        nuclearPercent: 0.0,
        solar: 0.8,
        oil: 56.2,
        gas: 43.0,
        perCapita: 15200,
        carbonIntensity: 710,
        energyIndependence: 2200,
        rank: 68,
        status: "lagging",
        color: "#dc2626",
        trend: "starting",
        keyProjects: ["Al-Dabdaba solar", "Shagaya renewable", "Oil dependence"],
        targetYear: 2030,
        targetRenewable: 15
    },

    "Qatar": {
        totalConsumption: 49.2,
        renewablePercent: 1.2,
        fossilFuelPercent: 98.8,
        nuclearPercent: 0.0,
        solar: 1.2,
        oil: 18.2,
        gas: 80.6,
        perCapita: 17200,
        carbonIntensity: 690,
        energyIndependence: 950,
        rank: 69,
        status: "lagging",
        color: "#dc2626",
        trend: "starting",
        keyProjects: ["Al-Kharsaah solar", "LNG exports", "Gas economy"],
        targetYear: 2030,
        targetRenewable: 20
    },

    "Oman": {
        totalConsumption: 34.2,
        renewablePercent: 2.4,
        fossilFuelPercent: 97.6,
        nuclearPercent: 0.0,
        solar: 2.4,
        oil: 18.2,
        gas: 79.4,
        perCapita: 6700,
        carbonIntensity: 620,
        energyIndependence: 650,
        rank: 70,
        status: "lagging",
        color: "#dc2626",
        trend: "starting",
        keyProjects: ["Green hydrogen", "Solar projects", "Wind farms"],
        targetYear: 2040,
        targetRenewable: 30
    },

    "Israel": {
        totalConsumption: 68.2,
        renewablePercent: 8.4,
        fossilFuelPercent: 91.6,
        nuclearPercent: 0.0,
        solar: 8.1,
        wind: 0.3,
        coal: 28.2,
        oil: 2.8,
        gas: 60.6,
        perCapita: 7400,
        carbonIntensity: 520,
        energyIndependence: 75,
        rank: 71,
        status: "lagging",
        color: "#ef4444",
        trend: "improving",
        keyProjects: ["Solar boom", "Gas discoveries", "Coal phaseout"],
        targetYear: 2050,
        targetRenewable: 30
    },

    "Jordan": {
        totalConsumption: 20.4,
        renewablePercent: 20.8,
        fossilFuelPercent: 79.2,
        nuclearPercent: 0.0,
        solar: 15.2,
        wind: 5.6,
        coal: 0.0,
        oil: 8.2,
        gas: 71.0,
        perCapita: 1950,
        carbonIntensity: 510,
        energyIndependence: 5,
        rank: 72,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Solar expansion", "Wind farms", "Energy imports"],
        targetYear: 2030,
        targetRenewable: 31
    },

    "Lebanon": {
        totalConsumption: 18.2,
        renewablePercent: 5.2,
        fossilFuelPercent: 94.8,
        nuclearPercent: 0.0,
        hydro: 5.2,
        solar: 0.0,
        coal: 0.0,
        oil: 94.8,
        gas: 0.0,
        perCapita: 2650,
        carbonIntensity: 680,
        energyIndependence: 10,
        rank: 73,
        status: "lagging",
        color: "#dc2626",
        trend: "crisis",
        keyProjects: ["Solar potential", "Wind projects", "Energy crisis"],
        targetYear: 2030,
        targetRenewable: 12
    },

    // Additional Countries
    "Ukraine": {
        totalConsumption: 128.4,
        renewablePercent: 12.8,
        fossilFuelPercent: 37.2,
        nuclearPercent: 50.0,
        hydro: 6.2,
        wind: 2.8,
        solar: 3.8,
        coal: 28.2,
        oil: 1.8,
        gas: 7.2,
        nuclear: 50.0,
        perCapita: 2900,
        carbonIntensity: 360,
        energyIndependence: 65,
        rank: 74,
        status: "transition",
        color: "#3b82f6",
        trend: "war-impacted",
        keyProjects: ["Nuclear safety", "Renewable rebuild", "Energy security"],
        targetYear: 2050,
        targetRenewable: 25
    },

    "Kazakhstan": {
        totalConsumption: 108.2,
        renewablePercent: 11.2,
        fossilFuelPercent: 88.8,
        nuclearPercent: 0.0,
        hydro: 10.8,
        wind: 0.2,
        solar: 0.2,
        coal: 69.8,
        oil: 6.2,
        gas: 12.8,
        perCapita: 5700,
        carbonIntensity: 710,
        energyIndependence: 190,
        rank: 75,
        status: "lagging",
        color: "#ef4444",
        trend: "slow",
        keyProjects: ["Wind potential", "Solar expansion", "Coal dominance"],
        targetYear: 2050,
        targetRenewable: 15
    },

    "Uzbekistan": {
        totalConsumption: 58.2,
        renewablePercent: 16.8,
        fossilFuelPercent: 83.2,
        nuclearPercent: 0.0,
        hydro: 16.2,
        solar: 0.4,
        wind: 0.2,
        coal: 4.2,
        oil: 1.8,
        gas: 77.2,
        perCapita: 1700,
        carbonIntensity: 520,
        energyIndependence: 120,
        rank: 76,
        status: "lagging",
        color: "#ef4444",
        trend: "improving",
        keyProjects: ["Solar projects", "Hydro expansion", "Gas exports"],
        targetYear: 2030,
        targetRenewable: 25
    },

    "Azerbaijan": {
        totalConsumption: 24.8,
        renewablePercent: 18.2,
        fossilFuelPercent: 81.8,
        nuclearPercent: 0.0,
        hydro: 17.8,
        solar: 0.2,
        wind: 0.2,
        oil: 8.2,
        gas: 73.6,
        perCapita: 2450,
        carbonIntensity: 480,
        energyIndependence: 250,
        rank: 77,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Wind expansion", "Solar growth", "Gas exports"],
        targetYear: 2030,
        targetRenewable: 30
    },

    "Belarus": {
        totalConsumption: 38.2,
        renewablePercent: 6.8,
        fossilFuelPercent: 16.2,
        nuclearPercent: 77.0,
        hydro: 0.8,
        wind: 0.2,
        solar: 0.8,
        biomass: 5.0,
        coal: 0.8,
        oil: 6.2,
        gas: 9.2,
        nuclear: 77.0,
        perCapita: 4000,
        carbonIntensity: 280,
        energyIndependence: 20,
        rank: 78,
        status: "transition",
        color: "#3b82f6",
        trend: "stable",
        keyProjects: ["New nuclear plant", "Biomass CHP", "Russian gas"],
        targetYear: 2050,
        targetRenewable: 12
    },

    "Bulgaria": {
        totalConsumption: 43.2,
        renewablePercent: 23.8,
        fossilFuelPercent: 42.8,
        nuclearPercent: 33.4,
        hydro: 9.2,
        wind: 6.8,
        solar: 5.2,
        biomass: 2.6,
        coal: 38.2,
        oil: 0.8,
        gas: 3.8,
        nuclear: 33.4,
        perCapita: 6200,
        carbonIntensity: 430,
        energyIndependence: 50,
        rank: 79,
        status: "transition",
        color: "#3b82f6",
        trend: "improving",
        keyProjects: ["Coal phaseout", "Solar expansion", "Nuclear modernization"],
        targetYear: 2050,
        targetRenewable: 27
    },

    "Serbia": {
        totalConsumption: 32.8,
        renewablePercent: 29.2,
        fossilFuelPercent: 70.8,
        nuclearPercent: 0.0,
        hydro: 28.8,
        wind: 0.2,
        solar: 0.2,
        coal: 65.8,
        oil: 1.2,
        gas: 3.8,
        perCapita: 4700,
        carbonIntensity: 680,
        energyIndependence: 70,
        rank: 80,
        status: "transition",
        color: "#3b82f6",
        trend: "slow",
        keyProjects: ["Renewable expansion", "Coal dependence", "EU integration"],
        targetYear: 2050,
        targetRenewable: 40
    }
};

// Energy Status Categories
const energyStatus = {
    leader: { min: 50, color: "#10b981", icon: "⚡" },
    transition: { min: 20, color: "#3b82f6", icon: "🔄" },
    lagging: { min: 0, color: "#ef4444", icon: "⚠️" }
};

// Make data available globally
if (typeof window !== 'undefined') {
    window.energyData = energyData;
    window.energyStatus = energyStatus;
}
